### ISSUE TITLE
QQ在启动时崩溃

### ISSUE THREAD

**Issue by ShirokoLEET** [nyaruhodoo/LiteLoader-StarWand#1]
加入此插件后 无法打开QQ 在log中无法看到报错 只有qq自带的崩溃检测
使用版本：QQ9.9.15-27333 Liteloader 1.2.2
![image](https://github.com/user-attachments/assets/2003efad-dae9-4d7d-8984-712ee657e5da)

**Comment by ShirokoLEET** [comment]
![Uploading d3f36481-7de1-4310-a23a-afc29ceb8e44.png…]()

**Comment by nyaruhodoo** [comment]
已修复

**Comment by Annabel0530** [comment]
目前安装插件之后还是会崩溃无法启动
使用版本：QQNT 9.9.12-25493 LiteLoader 1.2.2

**Comment by ShirokoLEET** [comment]
![image](https://github.com/user-attachments/assets/1411f886-2361-463e-b30e-58c3219b7c8a)
应该是只适配26909以上的qq

**Comment by Annabel0530** [comment]
👌🏻更到28418可以了
