### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by Annabel0530** [nyaruhodoo/LiteLoader-StarWand#2]
好用爱用，不知是否有办法将大图也以非文件的方式发送出去，旧版QQ还能双击点开转发强行发出，NTQQ真没头绪
![9 U6W5(JWUT5AFQCUNL OJY_tmb](https://github.com/user-attachments/assets/52f2ec10-9c46-469a-869d-68d212a75a7d)

**Comment by nyaruhodoo** [comment]
许愿人数≥10，才会考虑添加
亲，请再接再厉

**Comment by lileeli0** [comment]
许愿+1

**Comment by wsws19930315** [comment]
许愿+1

**Comment by dmarkdmark** [comment]
![Clip_2024-10-25_16-32-44](https://github.com/user-attachments/assets/75f2b201-1c39-4e47-accc-4857db7ddc98)

**Comment by wsws19930315** [comment]
> ![Clip_2024-10-25_16-32-44](https://private-user-images.githubusercontent.com/114052628/380078593-75f2b201-1c39-4e47-accc-4857db7ddc98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDU3MTcsIm5iZiI6MTcyOTg0NTQxNywicGF0aCI6Ii8xMTQwNTI2MjgvMzgwMDc4NTkzLTc1ZjJiMjAxLTFjMzktNGU0Ny1hY2NjLTQ4NTdkYjdkZGM5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwODM2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjg5YzY2Y2JkYmE0YmM1MGFiOTQ4NTY2YTdiYmI0MjYxZTJjYjBhZjQ2ZGFlNzFmNGViYWJiY2E1MWUzZTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nBZVTDjLmPFbYYtHoWQ5j_Xre0o2e8ge3hR410fL7Yk)

原来是这样许愿

**Comment by CrunchyCrunchyShark** [comment]
许愿+1

**Comment by mingyu0401** [comment]
许愿+114514

**Comment by nyaruhodoo** [comment]
等着吧，近期有点事做
事情完了，会把该功能作为第一优先级

**Comment by li08** [comment]
许愿+191810

**Comment by nyaruhodoo** [comment]
我一个这么喜欢发色图的都感觉这个没用，你们怎么这么需要啊
我服啦

**Comment by nyaruhodoo** [comment]
该功能在0.0.5版本中已经实现，不过据我测试上传超过10mb的图片用qq预览大概率会经常卡死几秒
所以确实不是很推荐上传大图片...

**Comment by Annabel0530** [comment]
实测目前没有遇到卡死，赞
一般可能是大图在QQ粘贴时同时另存了一张png导致的

**Comment by SNESNya** [comment]
pdd是吧
