### ISSUE TITLE
闪退  QQ版本: 9.9.15-26909 (64位)  

### ISSUE THREAD

**Issue by qdhjhb** [nyaruhodoo/LiteLoader-StarWand#5]
如题  安装是通过代码装的 使用release提示找不到  打开QQ在登录界面卡死闪退   是不是得换更高级的版本才行啊  以下是安装的插件
![image](https://github.com/user-attachments/assets/b2efee1f-ecb0-4c49-b273-9621e013ea06)

**Comment by nyaruhodoo** [comment]
你可以先尝试更新最新版
我没记错的话26909是可以运行的。。。

**Comment by xBoyMinemc** [comment]
9.9.15-27597
这个版本没事，希望这个信息可以帮到你。

**Comment by nyaruhodoo** [comment]
因没有进一步提供相关细节暂时关闭该问题
或许只是你安装出了错误...

**Comment by qdhjhb** [comment]
> 因没有进一步提供相关细节暂时关闭该问题 或许只是你安装出了错误...

用新版本解决了
