### ISSUE TITLE
向”我的手机”发送图片视频文件失败

### ISSUE THREAD

**Issue by cdwc233** [nyaruhodoo/LiteLoader-StarWand#7]
QQ版本: 9.9.17-30594 (64位)
LiteLoader版本: 1.2.3
星之杖版本：0.0.6 (仓库代码包)

![image](https://github.com/user-attachments/assets/f8568693-b88c-454c-8e63-17f58b77cf24)
向"我的手机"发送任何图片格式文件时，预览图显示空白 (除非之前已经发送过同样的图片存在过预览图) 且一直转圈圈，一段时间后显示红色感叹号，发送失败；
发送视频格式文件时，能显示预览图但发送一直转圈圈，一段时间后显示红色感叹号发送失败；
发送其他格式文件无异常，卸载星之杖后该问题不再出现。

**Comment by nyaruhodoo** [comment]
一开始就没考虑到发送给手机
以修复，更新0.0.7即可

发送给手机的消息将会和原逻辑一致，不会有任何特殊处理
