### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by Tanq0213** [nyaruhodoo/LiteLoader-StarWand#8]
超过100兆的视频，会发送不出去。可以加个判断吗，超过100兆就不管，按原来的以文件的形式发送
![image](https://github.com/user-attachments/assets/152e3ebc-a2d1-494c-8200-8e339d18f233)
![image](https://github.com/user-attachments/assets/4e17f774-27d7-48ba-8815-857c50f5ac7b)

**Comment by nyaruhodoo** [comment]
晚些会修复
你们真是什么都往群里发...

更新0.0.8即可解决
