### ISSUE TITLE
建议设置选项内的视频静音

### ISSUE THREAD

**Issue by Keeperorowner** [nyaruhodoo/LiteLoader-StarWand#9]
在图书馆里突然好大的声音，获得了所有人的目光

**Comment by nyaruhodoo** [comment]
不可能，绝对不可能
如果你觉得默认的0.05音量还是过高，那么提供以下几个解决办法
- 移除`LiteloaderQQNT\plugins\LiteLoader-StarWand\assets\movie.mp4`
- 调整音量`LiteloaderQQNT\plugins\LiteLoader-StarWand\src\renderer\configPage\index.ts` 30 行 （需要编译）
